services:
    runner:
      image: github-action-runner-image:${tag}
      build:
        context: ./docker-github-runner
        args:
          - runnerVersion=${runnerVersion}
          - runnerUrl=${runnerUrl}
      container_name: github-action-runner-${name}
      environment:
        organization: ${organization}
        runnerToken: ${runnerToken}
      privileged: true
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
