on:
  push:
    branches:
      - main
      - 'feature/**'

jobs:
  testJob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run docker test-workflow
        run: |
          docker run hello-world
        shell: bash
