on:
  push:
    branches:
      - main
      - 'feature/**'

jobs:
  testJob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run build script
        run: |
          chmod +x ./build_local.sh
          ./build_local.sh
        shell: bash
        env:
          githubToken: ${{ secrets.PAT_TOKEN }}
          repo: docker-eclipse
