on:
  push:
    branches:
      - main
      - 'feature/**'

jobs:
  testJob:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Run docker test-workflow
        run: |
          docker run --rm hello-world
        shell: bash
